#!/usr/bin/env bash
# Changes localhost resolution and adds facebook.com
cp /etc/hosts /tmp/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /tmp/hosts.new
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
cat /tmp/hosts.new > /etc/hosts
