#!/usr/bin/env bash
# Changes localhost IP and facebook.com IP in /etc/hosts
sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > /tmp/hosts_new
echo "8.8.8.8 facebook.com" >> /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts
